# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

DISTUTILS_USE_PEP517=setuptools
REPO_URI="https://github.com/wookayin/gpustat/archive/refs/tags/v1.1.1.tar.gz"
SOURCEFILE="${P}.tar.gz"
PYTHON_COMPAT=( python3_{11..13} )

inherit pypi

DESCRIPTION="GPU-based statistical functions"
HOMEPAGE="https://github.com/wookayin/gpustat"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND="dev-python/blessed
         dev-python/nvidia-ml-py"

src_install() {
    default_src_install

    # Move the installed scripts to /usr/local/bin
    # Assuming the scripts are installed in ${D}/usr/bin
    # Adjust the path if necessary based on where the scripts are installed
    if [[ -d "${D}/usr/bin" ]]; then
        mv "${D}/usr/bin/gpustat" "${D}/usr/local/bin/"
    fi    
}
